.Dd $Mdocdate$
.Dt GOMOKU 1
.Os
.Sh NAME
.Nm gomoku
.Nd Gomoku game implementation
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Pp
.Nm
is an implementation of the classic Gomoku game in C.
.Pp
The objective of the game is to be first select five cells in row on a nineteen by nineteen grid. Players take turns making moves on the board.
.Pp
The game controls are as follows:
.Bl -tag -width indent
.It Ic Key Up, k
Move up one cell
.It Ic Key Down, j
Move down one cell
.It Ic Key Left, h
Move left one cell
.It Ic Key Right, l
Move right one cell
.It Ic Space
Make a move
.El
.Sh SEE ALSO
.Xr gomoku 6
.Sh AUTHORS
.An Ben Raskin Aq Mt ben [at] 0x1bi [dot] net
